config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats do
    resources :bookings
  end

  resources :photos, only: [:create]
  resources :profiles, only: [:show, :edit, :update,]

  get '/dashboard' => 'profiles#show'

  resources :favourites, only: [:create, :index, :destroy]

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  has_many :bookings
  belongs_to :user
  # full_address method was added because our address doesn't have the city
  geocoded_by :full_address
  after_validation :geocode, if: :address_changed?

  # accepts_nested_attributes_for :photos

  def full_address
    address + ' ' + city
  end

  after_create :generate_photo

  def generate_photo
    Photo.create(flat: self)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :flat, only: [:show, :edit, :destroy, :update]

  def index
    @flats = Flat.where(city: params[:city])
    @city = params[:city]


        # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end

  end

  def show
# I'm using [@flat] because I need only this specific flat but I could use an array of flats also.
    @markers = Gmaps4rails.build_markers([@flat]) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      p = @flat.photos.first
      p.cloudinary = params[:flat][:photo][:cloudinary]
      p.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update_attributes(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def destroy
    flat.destroy
    redirect_to root_path
  end


  private

  def flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:address, :city, :price, :rooms, :user_id,
     photos_attributes: [:id, :file_key , :cloudinary, :cloudinary_cache, :description] )
  end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1 class="text-center">Edit Flat</h1>
<div class="container">

<%= simple_form_for @flat do |f| %>
<%= f.input :address %>
<%= f.input :city %>
<%= f.input :price %>
<%= f.input :rooms %>
<%= f.button :submit %>

<% end %>
</div>

app/views/flats/index.html.erb
<h1>Flats available in <%= @city %></h1>


<div class="media">
  <div class="media-body">
    <div class="media-section">
      <div class="container">
        <div class="row">

          <% @flats.each do |flat| %>
          <div class="col-xs-12 col-md-4">
            <%= link_to flat_path(flat) do %>
            <div class="card" style="background-image: url('<%= image_url flat.photos.first.try(:cloudinary) %>');" >
                <div class="card-category"><%= flat.price %>€</div>
                <div class="card-description"> <%= flat.address %> </div>
                <img class="card-user avatar avatar-large" src=" <%= flat.user.profile.photo %> ">
              <% favourite = Favourite.find_by user_id: current_user, flat_id: flat %>
              <% if Favourite.exists?(user_id: current_user) &&
                    Favourite.exists?(flat_id: flat) %>
                    <%= link_to favourite_path(id: favourite), method: :delete  do %>
                      <div class="card-heart">
                        <i class="fa fa-heart"> </i>
                      </div>
                  <% end %>
              <% else %>
                  <%= link_to favourites_path(flat: flat), method: :post do %>
                    <div class="card-heart-o">
                      <i class="fa fa-heart-o"> </i>
                    </div>
                  <% end %>

              <% end %>

            </div>

            <% end %>

          </div>

          <% end %>
        </div>
      </div>


    </div>
  </div>

  <div class="media-aside">
    <div class="media-section">
     <div id="map" style="width: 400px; height: 600px;"></div>
   </div>
 </div>

</div>

<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).on('ready', function() {
handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function(){
markers = handler.addMarkers(<%= raw @markers.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
});
})
<% end %>
<% end %>

app/views/flats/new.html.erb
<h1 class="text-center">New Flat</h1>
<div class="container">

  <%= simple_form_for @flat do |f| %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :price %>
    <%= f.input :rooms %>

    <%= f.simple_fields_for Photo.new do |p| %>
      <%= p.input :cloudinary %>
      <%= p.input :cloudinary_cache, as: :hidden %>
    <% end %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/flats/show.html.erb
<!-- <div class="xxxx" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('images/background.jpg');">
        <div class="banner-content">
          <h1>WELCOME HOME</h1>
          <p>Rent unique places to stay from local hosts in 190+ countries.</p>
          <a class="btn btn-primary btn-lg">How it works</a>
        </div>
      </div>

    -->
<div class="media-section"></div>
<div class="media-aside text-center">
<div class="media-section jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
          <h3><%= @flat.address %></h3>
          <h3><%= @flat.city %></h3>
          <h3>Price/night: €<%= @flat.price %></h3>
          <h3>Number of rooms: <%= @flat.rooms %></h3>

          <% @flat.photos.each do |photo| %>

          <div> <%= cl_image_tag photo.cloudinary, height: 400, width: 400, crop: :fill %>
          </div>

          <% end %>

        </div>
      </div>
    </div>



<div class="media-section"></div>
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-4 col-sm-4">

       <% if current_user %>
          <% if current_user.id == @flat.user_id %> <!-- if current user is the owner of this flat -->

              <%= simple_form_for Photo.new, html: { class: 'form-horizontal' } do |f| %>
                <%= f.input :flat_id, :as => :hidden, :input_html => { :value => @flat.id } %>
                <%= f.label "upload another photo?"%>
                <%= f.input :cloudinary, label: false %>
                <%= f.input :cloudinary_cache, as: :hidden %>
              <%= f.button :submit %>

              <% end %>

              <div class="media-section"></div>
              <div class="media-aside form-inline">

              <%= link_to "Go to dashboard", profile_path, class:"btn btn-warning", type:"button" %>

              <%= link_to "Edit", edit_flat_path(@flat), class:"btn btn-warning", type:"button" %>

              <%= link_to "Delete Flat", flat_path(@flat), method: :delete, class:"btn btn-warning", type:"button" %>

              </div>
              </div>

          <% else %>
              <p class="btn btn-default"><%= link_to "Book It", new_flat_booking_path(@flat) %></p>
          <% end %>

      <% end %>

      </div>

    </div>
  </div>
  </div>
  </div>




  <div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>