config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats do
    resources :bookings
  end

  resources :photos, only: [:create]
  resources :profiles, only: [:show, :edit, :update,]

  get '/dashboard' => 'profiles#show'

  resources :favourites, only: [:create, :index, :destroy]

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :flat
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    favourite = Favourite.new
    favourite.user = current_user
    favourite.flat_id = params[:flat].to_i
    favourite.save
    redirect_to :back
  end

  def index
    @favourites = Favourite.all
  end

  def destroy
    f = Favourite.find(params[:id])
    f.destroy
    redirect_to :back
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/index.html.erb
<h1>My Favourite Flats</h1>

<div class="container">
  <div class="row">

    <% @favourites.each do |favourite| %>
      <% flat =  favourite.flat %>
      <div class="col-xs-12 col-md-4">
        <%= link_to flat_path(flat) do %>
        <div class="card" style="background-image: url('<%= image_url flat.photos.first.try(:cloudinary) %>');" >
          <div class="card-category"><%= flat.price %>€</div>
          <div class="card-description"> <%= flat.address %> </div>
          <img class="card-user avatar avatar-large" src=" <%= flat.user.profile.photo %> ">
        </div>
        <% end %>

        <% if Favourite.exists?(user_id: current_user) && Favourite.exists?(flat_id: flat) %>

            <%= link_to favourite_path(flat: flat), method: :delete do %>
            <div class="card-heart">
              <i class="fa fa-heart"> </i>
            </div>
            <% end %>

        <% else %>
            <%= link_to favourites_path(flat: flat), method: :post do %>
            <div class="card-heart-o">
              <i class="fa fa-heart-o"> </i>
            </div>
            <% end %>

        <% end %>
      </div>
    <% end %>
  </div>

</div>