config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats do
    resources :bookings
  end

  resources :photos, only: [:create]
  resources :profiles, only: [:show, :edit, :update,]

  get '/dashboard' => 'profiles#show'

  resources :favourites, only: [:create, :index, :destroy]

end

app/views/shared/_features.html.erb
<h2>How it works</h2>
<div class="container text-center padded features">
  <div class="row">
  <div class="col-xs-12 col-sm-6 col-md-3">
<img alt="" src="../assets/images/globe.png"></img>
<h2>Discover the world</h2>
<p>The earth is your new home.</p>
</div>
 <div class="col-xs-12 col-sm-6 col-md-3">
<img alt="" src="images/dollar.png"></img>
<h2>Pay online</h2>
<p>No cash issues anymore.</p>
</div>
 <div class="col-xs-12 col-sm-6 col-md-3">
<img alt="" src="images/beer.png"></img>
<h2>Meet people</h2>
<p>Discover new culture and lifestyle.</p>
</div>
 <div class="col-xs-12 col-sm-6 col-md-3">
<img alt="" src="images/heart.png"></img>
<h2>Share and love</h2>
<p>Join a community you will love.</p>
</div>
</div>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="text-center padded">
    <ul class="list-inline">
    <li>
      <a href="www.youtube.be/user/Airbnb">
        <i class="fa fa-youtube"></i>
      </a>
    </li>
    <li>
      <a href="">
        <i class="fa fa-instagram"></i>
      </a>
    </li>
    <li>
      <a href="https://www.facebook.com/airbnb/">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a href="https://twitter.com/Airbnb">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    </ul>
    <p>This is our awesome website - Ricardo, Nimi, Binita, and Prayag</p>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "Airbnb_Logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


    <!-- Button (call-to-action) -->
<!--     <div class="navbar-wagon-item navbar-wagon-button btn">
    <%= link_to "Dashboard", dashboard_path %>
    </div> -->


    <!-- Notification -->


    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag current_user.profile.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>

            <% if(current_user.profile) %>

            <%= link_to edit_profile_path(current_user, current_user.profile) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Edit Profile" %>
            <% end %>

            <%= link_to profile_path(current_user, current_user.profile) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Dashboard" %>
            <% end %>

            <li>
              <%= link_to new_flat_path do %>
              <i class="fa fa-plus"></i>  <%= t ".profile", default: "Add a flat" %>
              <% end %>
            </li>

            <% else %>

            <%= link_to new_profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "New Profile" %>
            <% end %>

            <% end %>

          </li>

          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>

        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_subscribe.html.erb
<div id="newsletter" class="text-center padded">
    <h2>Get news from us</h2>
    <p>Leave us your mail and get news from us.</p>
    <form action="#" class="form-inline">
  <input type="email" class="form-control" placeholder="martin@gmail.com"></input>
  <input type="submit" value="Subscribe" class="btn btn-primary btn bordered btn-bordered primary"></input>
</form>
</div>